### ISSUE TITLE
Deassembled PDM_Filter has align fault

### ISSUE THREAD

**Issue by AleCher** [piratfm/codec2_m4f#1]
Hi, may be I make mistake, but my program faults at pdm_filter.S line 90. It happen because unaligin access to dword_F8. When I added '.align 8' before dword_F8 problem solved

**Comment by piratfm** [comment]
Yes, I have same problem, when I started using gcc-arm-embedded instead of CodeSourcery. I fonund c-based pdm filter as replacement for that asm file. You can find it in codec2 tree in the lib directory. It  works same as disassembled, but if you want to customize filter bandwidth, you need to recalculate coefficients list.

**Comment by AleCher** [comment]
ST lib works fine and faster, my dirty patch

`````` patch
*** 155,160 ****
--- 155,161 ----
  @; End of function PDM_Filter_Init

  @; ---------------------------------------------------------------------------
+ .align 8
  dword_F8:
        .word 0x51EB851F, 0x40191EB8
  @;dword_100:```
``````
